name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files to check project name
        run: ls -la

      - name: Build for Simulator (TEST ONLY - NO SIGNING)
        run: |
          xcodebuild build -project "iosProjectTemplate.xcodeproj" \
            -scheme "iosProjectTemplate" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            -configuration Release
