name: Build iOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # 👉 就是这一步！解决你所有错误
      - name: Install Carthage
        run: brew install carthage

      # 👉 纯编译，不指定设备
      - name: Build Project
        run: |
          xcodebuild build \
            -project "iOSProject.xcodeproj" \
            -scheme "iOSProject" \
            -sdk iphonesimulator \
            -configuration Debug \
            SKIP_SWIFTLINT=YES
